/**
 * EWO-038 (Task 8) — deterministically generates the full text of
 * `src/data/shipImageRegistry.ts` from the validated, matched canonical
 * maintenance dataset. Pure string-in/string-out — never touches the
 * filesystem itself (the CLI decides whether/where to write it), so this
 * is directly unit-testable.
 */
export interface RegistryEntryInput {
  registryKey: string
  url: string
}

const FILE_HEADER = `/**
 * EWO-021A / EWO-038 — Canonical Ship Image URL Registry.
 *
 * GENERATED FILE — do not hand-edit. Regenerated by
 * \`npm run ship-images:generate\` from the Commander-maintained
 * \`data-maintenance/ship-images/ship-image-master.csv\` (see
 * scripts/shipImages/ for the full import/generation pipeline, and
 * docs/ASSET_PIPELINE.md for the Commander maintenance workflow).
 *
 * ── Keys ──────────────────────────────────────────────────────────────
 * Each key is a canonical ship image-resolution key exactly as
 * \`src/utils/resolveShipImage.ts\` looks it up (a seed id, a deep-imported
 * ship's raw StarBreaker entity class, or a Mission M-012 catalog-only
 * entity class) — never hand-construct one; the generator derives it
 * directly from \`selectableShipDefinitions\`.
 *
 * ── Values ────────────────────────────────────────────────────────────
 * Official RSI-hosted image URLs. Must be absolute HTTPS URLs from an
 * approved RSI image host — a malformed or disallowed value is rejected
 * at generation time, never written here.
 *
 * ── What NOT to do ───────────────────────────────────────────────────
 * - Never hand-edit this file — edit
 *   data-maintenance/ship-images/ship-image-master.csv's \`rsi_image_url\`
 *   column instead, then re-run \`npm run ship-images:generate\`.
 * - A missing entry is not an error — it falls through to the ship's
 *   existing image source, then the universal fallback placeholder
 *   (src/constants/shipImage.ts, unchanged by this pipeline).
 */
export const SHIP_IMAGE_URLS: Readonly<Record<string, string>> = {
`

const FILE_FOOTER = `}
`

/** Generates the complete file text. Entries are sorted by registryKey
 * (stable, deterministic — Task 6/8) and de-duplicated by key (the last
 * occurrence wins, though the CLI itself is expected to never pass
 * duplicate keys in the first place — see Task 9's diff/reconciliation
 * step, which is where a duplicate would actually be caught and reported). */
export function generateRegistryFileContent(entries: RegistryEntryInput[]): string {
  const byKey = new Map<string, string>()
  for (const entry of entries) byKey.set(entry.registryKey, entry.url)
  const sortedKeys = Array.from(byKey.keys()).sort((a, b) => a.localeCompare(b))

  const body = sortedKeys.map((key) => `  ${formatKey(key)}: ${JSON.stringify(byKey.get(key))},\n`).join('')
  return FILE_HEADER + body + FILE_FOOTER
}

/** A canonical id is only ever a valid JS identifier or requires quoting
 * (e.g. "135c" starts with a digit) — quote whenever it isn't a bare
 * identifier, matching the existing hand-written file's own style. */
function formatKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key)
}
